spring.application.name=Tymnt

spring.datasource.url=jdbc:mysql://localhost:3306/tymnt_db
spring.datasource.username=root
spring.datasource.password=Vikash@#@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#server.address=192.168.31.189
#server.address=10.20.18.10
server.address=10.132.112.108
server.port=9090
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
management.endpoints.web.exposure.include=mappings
